      server:
        port: 8080
        servlet:
          context-path:

      spring:
        datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql:///postgres
          username: postgres
          password: Test123
          hikari:
            data-source-properties:
              socketFactory: com.google.cloud.sql.postgres.SocketFactory
              cloudSqlInstance: daring-anagram-419908:us-central1:shortenerurl

        jpa:
          hibernate:
            ddl-auto: create-drop
          properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
